name: Releases

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8
          check-latest: true

      - name: Install latest build tools
        run: |
          echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "build-tools;33.0.1" --sdk_root=${ANDROID_SDK_ROOT}

      - name: Install NDK
        run: |
          echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;22.1.7171670" --sdk_root=${ANDROID_SDK_ROOT}

      - name: Build the app
        run: |
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace

      - name: Uploading Artifact
        uses: actions/upload-artifact@v3
        with:
          path: ./app/build/outputs/apk/debug/app-debug.apk

      - name: Releases
        uses: softprops/action-gh-release@v1
        with:
          body: Bump Version
          files: |
            ./app/build/outputs/apk/debug/app-debug.apk
